name: zoozitest
description: "An app for Zoozi"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  async: ^2.13.0
  auto_route: ^10.1.0+1
  cupertino_icons: ^1.0.8
  dartx: ^1.2.0
  flutter_bloc: ^9.1.1
  flutter_local_notifications: ^19.2.1
  flutter_screenutil: ^5.9.3
  get_it: ^8.0.3
  injectable: ^2.5.0
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  auto_route_generator: ^10.1.0
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  flutter_gen_runner: ^5.10.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  injectable_generator: ^2.7.0
  logging: ^1.3.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true